version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      default:
        { }
      clickhouse-network:
        ipv4_address: 172.23.0.8
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9094:9094
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "gen-logs:1:1,online_user:1:1"
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.5
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    stdin_open: false
    tty: false
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
      # - KAFKA_CLUSTERS_0_READONLY=true
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.6
  clickhouse01:
    image: yandex/clickhouse-server
    # links:
    #   - kafka
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    # ports:
    #   - "8123:8123"
    #   - "9000:9000"
    #      - "9009:9009"
    ulimits:
      nproc: 65535
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./clickhouse01:/etc/clickhouse-server
    environment:
      KAFKA_BROKER: "kafka:9092"
  clickhouse02:
    image: yandex/clickhouse-server
    # links:
    #   - kafka
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    # ports:
    #   - "8123:8123"
    #   - "9000:9000"
    #      - "9009:9009"
    ulimits:
      nproc: 65535
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./clickhouse02:/etc/clickhouse-server
    environment:
      KAFKA_BROKER: "kafka:9092"
  clickhouse03:
    image: yandex/clickhouse-server
    # links:
    #   - kafka
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    # ports:
    #   - "8123:8123"
    #   - "9000:9000"
    #      - "9009:9009"
    ulimits:
      nproc: 65535
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./clickhouse03:/etc/clickhouse-server
    environment:
      KAFKA_BROKER: "kafka:9092"
  clickhouse04:
    image: yandex/clickhouse-server
    links:
      - kafka
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.14
    # ports:
    #   - "8123:8123"
    #   - "9000:9000"
    #      - "9009:9009"
    ulimits:
      nproc: 65535
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - ./clickhouse04:/etc/clickhouse-server
    environment:
      KAFKA_BROKER: "kafka:9092"
  clickhouse-client:
    image: yandex/clickhouse-client
    depends_on:
      - clickhouse01
      - pyspark
      - zookeeper
    volumes:
      - ./db:/db
    entrypoint: /bin/bash /db/go.sh
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.9
    environment:
      KAFKA_BROKER: "kafka:9092"
  generator:
    image: klntsky/generator:1.0
    stdin_open: true
    tty: true
    depends_on:
      - kafka
    network_mode: host
    environment:
      KAFKA_BROKER: "localhost:9094"
  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: vertamedia-clickhouse-datasource,grafana-worldmap-panel
    # networks:
    #   clickhouse-network:
    #     ipv4_address: 172.23.0.50
  pyspark:
    image: klntsky/spark-env:1.0 # jupyter/pyspark-notebook:latest
    hostname: pyspark
    container_name: pyspark
    ports:
      - 8888:8888
      - 4040:4040
    depends_on:
      - kafka
      - zookeeper
      - generator
      - clickhouse01
      - clickhouse02
      - clickhouse03
      - clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.7
    entrypoint: /usr/bin/env python /spark/run.py
    volumes:
      - ./spark:/spark
    #volumes:
    #  - pySpark: pySpark/
    # depends_on:
    #   - zookeeper

networks:
  clickhouse-network:
    ipam:
      config:
        - subnet: 172.23.0.0/24
