name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache dependencies (Unix)
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-store-${{ hashFiles('generator/stack.yaml.lock') }}-${{ hashFiles('generator/generator.cabal') }}

      - name: Build generator
        run: cd generator && stack build

      - name: Package generator
        shell: bash
        run: |
          mkdir package
          cd generator
          dir=$(stack path --dist-dir)/build/generator
          [[ -e "$dir/generator" ]] && cp "$dir/generator" ../package/myRetroGenerator
          cd ..
          cp -r static template package/
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: generator-${{ runner.os }}
          path: package
